[project]
name = "lang-yatp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-ollama>=0.3.10",
    "langgraph>=0.6.8",
    "langgraph-supervisor>=0.0.29",
    "langsmith>=0.4.32",
]
